### PR TITLE
fully qualify Witchcraft.Apply.then/2 to avoid name conflict in Elixir 1.12+

### PR DESCRIPTION
**Pull request by baseballlover723**
## Summary
Elixir 1.12 introduces a new kernel method: `Kernel.then/2`, this causes witchcraft to not compile on Elixir 1.12+ with 
```== Compilation error in file lib/witchcraft/foldable.ex ==
** (CompileError) lib/witchcraft/foldable.ex:751: function then/2 imported from both Witchcraft.Apply and Kernel, call is ambiguous
    (elixir 1.12.0-rc.1) src/elixir_dispatch.erl:42: :elixir_dispatch.import_function/4
    (elixir 1.12.0-rc.1) src/elixir_fn.erl:76: :elixir_fn.capture_import/4
    (stdlib 3.14.2) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14.2) lists.erl:1359: :lists.mapfoldl/3
```
This PR fully qualifies `Witchcraft.Apply.then/2` so that `then/2` is no longer ambiguous. 

This PR fixes/implements the following **bugs/features**

* [ ] Support Elixir 1.12+

Explain the **motivation** for making this change. What existing problem does the pull request solve?
You can't use witchcraft on Elixir 1.12+.

## Test plan (required)

Run the tests with Elixir 1.12.2

## Closing issues

Fixes #

## After Merge
* [ ] Does this change invalidate any docs or tutorials? _If so ensure the changes needed are either made or recorded_
* [ ] Does this change require a release to be made? Is so please create and deploy the release

### CODE REVIEW

File: lib/witchcraft/apply.ex [hunk 1]
```diff
@@ -378,8 +378,8 @@ defclass Witchcraft.Apply do
   ## Examples
 
       iex> [1, 2, 3]
-      ...> |> then([4, 5, 6])
-      ...> |> then([7, 8, 9])
+      ...> |> Witchcraft.Apply.then([4, 5, 6])
```
Comment (baseballlover723) [inline lib/witchcraft/apply.ex:381]: Theres probably a better way to fix this so that we can keep it as `then(...)` instead of `Witchcraft.Apply.then(...)`

Comment (trevorite) [reply lib/witchcraft/apply.ex:381]: When name conflict happens with Elixir's core modules like `Kernel`, I think it's better to specify full module name like this.

File: lib/witchcraft/foldable.ex [hunk 2]
```diff
@@ -30,7 +30,7 @@ defclass Witchcraft.Foldable do
   alias __MODULE__
   alias Witchcraft.{Apply, Ord, Monad, Monoid, Semigroup, Unit}
 
-  import Kernel, except: [length: 1, max: 2, min: 2]
+  import Kernel, except: [length: 1, max: 2, min: 2, then: 2]
```
Comment (trevorite) [inline lib/witchcraft/foldable.ex:33]: `Kernel.then/2` seems important like a pipe operator, so I think it's better not to except it. 
How do you think?
